### ISSUE TITLE
LambdaExecutionRole creation error

### ISSUE THREAD

**Issue by scalvanese452** [aws-samples/aws-health-aware#1]
Policy statement must contain resources. (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID:redacted ; Proxy: null)

**Comment by scalvanese452** [comment]
looks like it doesn't work using email only.  If I put a value in Microsoft it finishes.

**Comment by jordanaroth** [comment]
> looks like it doesn't work using email only. If I put a value in Microsoft it finishes.

Ok, taking a look now.

**Comment by jordanaroth** [comment]
> Policy statement must contain resources. (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID:redacted ; Proxy: null)

Thanks for pointing this out. Issue has now been fixed and pushed. I explained the issue in the release notes as well if you're interested. Take care and thanks for taking the time to try it out.
