### ISSUE TITLE
Skip alerts for some Event Types

### ISSUE THREAD

**Issue by benrobinsonsonos** [aws-samples/aws-health-aware#14]
In the case of noisy alerts, looking for a way to reduce the noise by excluding some event types from generating alerts (e.g. AWS_VPN_SINGLE_TUNNEL_NOTIFICATION,AWS_VPN_REDUNDANCY_LOSS). 

Forked the repo and added an attempt at:
https://github.com/benrobinsonsonos/aws-health-aware/blob/b60138a73b8ba3dea2695eafa503b140324c190a/handler.py#L48
https://github.com/benrobinsonsonos/aws-health-aware/blob/b60138a73b8ba3dea2695eafa503b140324c190a/handler.py#L120

**Comment by jordanaroth** [comment]
You can select certain event types from the CFN.

**Comment by benrobinsonsonos** [comment]
@jordanaroth I may have mislabeled this issue by using EventType, which in the context of AHA accepts the values "issue | accountNotification | scheduledChange". Within the AHA EventType, "issue" category, there are many noisy issues. This is about picking which ones to squelch, (e.g. AWS_VPN_SINGLE_TUNNEL_NOTIFICATION, AWS_DS_OPERATIONAL_ISSUE). **Nothing against AD Connector, just don't need to know about those issues.

**Comment by wellermann** [comment]
> You can select certain event types from the CFN.

@jordanaroth Can you elaborate on this? The noise from these VPN notifications prevent me from using AHA. I see that we can select AWSHealthEventType but that's not really the same. We want everything except the same as @benrobinsonsonos (AWS_VPN_SINGLE_TUNNEL_NOTIFICATION,AWS_VPN_REDUNDANCY_LOSS)
