### ISSUE TITLE
Slack Workflow creation example image has typo

### ISSUE THREAD

**Issue by andrewjhumphrey** [aws-samples/aws-health-aware#18]
The [Creating a Slack Webook](https://github.com/aws-samples/aws-health-aware#creating-a-slack-webhook-url) URL section has an typo in the [example image for the workflow option](https://github.com/aws-samples/aws-health-aware/blob/main/readme-images/workflow.png?raw=1):

The `status` variable is duplicated against the both the `start_time` and the `status` labels.

**Comment by jordanaroth** [comment]
Thank you, will fix.

**Comment by andrewcr7** [comment]
Fixed in https://github.com/aws-samples/aws-health-aware/commit/79c855790c45f8587792bcc52a60093632512a2e
