### ISSUE TITLE
CloudTrail AccessDenied entry, for any unconfigured secret

### ISSUE THREAD

**Issue by ylosonci** [aws-samples/aws-health-aware#19]
Another user reported to me that they receive many "AccessDenied" entries in Cloudtrail.
Upon testing this in my account environment, I was able to replicate this. 

Essentially, for any endpoint not configured, I receive a Cloudtrail entry with access denied stating that the role for AHA does not have access for "null" secret:
"<role> is not authorized to perform: secretsmanager:GetSecretValue on resource: ChimeChannelID because no identity-based policy allows the secretsmanager:GetSecretValue action","requestParameters":null,"responseElements":null" 

For them it's an issue because their SIEM is monitoring for those kind of events.

I want to know if this is by design, since I see that handler.py, when it's checking if there is a configured endpoint - is set to look for AccessDenied error coming from the client.

**Comment by jordanaroth** [comment]
This is expected. Please whitelist the error(s)
