### ISSUE TITLE
Notifications not associated to a region

### ISSUE THREAD

**Issue by hernan-fernandez** [aws-samples/aws-health-aware#2]
Hello Jordan. The solutions is working great in ms-teams. Thanks!

I've configured a couple of regions of my interest, I see some notifications doesn't appear when they are not associated to a region, do I need to select global for this?. What will happen if I select "us-east-1,us-east-2, global". I'll receive all the events world wide or only us-east-1,us-east-2 + those not associated to a region?

thanks

**Comment by jordanaroth** [comment]
> Hello Jordan. The solutions is working great in ms-teams. Thanks!
> 
> I've configured a couple of regions of my interest, I see some notifications doesn't appear when they are not associated to a region, do I need to select global for this?. What will happen if I select "us-east-1,us-east-2, global". I'll receive all the events world wide or only us-east-1,us-east-2 + those not associated to a region?
> 
> thanks

Yes, global should pick up everything else when it's not affecting any specific region.
