### ISSUE TITLE
Reminders of AWS_EC2_INSTANCE_STOP_SCHEDULED

### ISSUE THREAD

**Issue by JoshLoganSonos** [aws-samples/aws-health-aware#24]
Can this monitor be extended to repeat notifications of upcoming AWS_EC2_INSTANCE_STOP_SCHEDULED alerts.
Possibly in a reverse fibonacci sequence - 13, 8, 5, 3, 2, 1.

It would also be nice if the instance NAME was pulled from the Name Tag.

**Comment by jordanaroth** [comment]
We pull directly from the AWS Health API, we can't generate additional messages outside of what is sent from there. Will ask the EC2 team about this though.
