### ISSUE TITLE
Clarify docs a bit: Enabling HEALTH API on Org Level

### ISSUE THREAD

**Issue by timogoosen** [aws-samples/aws-health-aware#28]
Could you please update the docs a bit just to clarify the following, I think it might be useful for other people:

1. When enabling the Health API, when referring to the "management" account, does this refer to the payeer account?
2. When making use of the Health API (when it was enabled on an organizational level), should one access the API from the payeer account itself or can you make use of account that is below the payeer account in terms of account hierarchy, or perhaps even access it from one of the member accounts?

**Comment by jordanaroth** [comment]
Apologies for the delay.

1. The management account is the top level account of the AWS organization. This could be the payer account, but some customers have multiple payers. If you're logged into a member account, when you go to AWS Organizations in the console it will tell you that you are in an Organization and tell you the management account ID.

2. When using Organization View Health API (which has all the member account roll their health events up to it), you'll want to have the health API poll the management account. You can install AHA in the management account directly OR you can install AHA in a member account within the organization and give it the ability to assume a role that can query the management account. Those deployment options are outlined in the readme, as the member account deployment requires additional steps to create the assume role functions.

**Comment by andrewcr7** [comment]
Following up on this question.  AWS Health released the delegated administrator feature for AWS Organizations 
https://aws.amazon.com/about-aws/whats-new/2023/07/aws-health-delegated-administrator/

You can now use AWS Health Organizational View Health API (or see the same information as Health events on EventBridge in the delegated admin account).  AHA can take advantage of this as well, first enable the member account you want as delegated admin, then deploy AHA in Organizational mode in that account.
