### ISSUE TITLE
How to get notification from event bus ARN 

### ISSUE THREAD

**Issue by adnanmansuri44** [aws-samples/aws-health-aware#29]
HI, 
We want this notification in the email, where the only option to get it via SES or event bus ARN then SNS. SES required email verification and exchange policy to be allowed for delivery which is difficult 

We want to explore event bus option. after the event is received on the event bus it should trigger to SNS, SQS or any other service which required event pattern to be created. What will be event pattern sample or parameter to get that all events to SNS or SQS from event bus? and it should be in json format. So is lambda sending events into json format?

Please assist

Adnan

**Comment by gmridula** [comment]
Thank you Adnan for your feedback. We are currently making changes on how the health events get pushed to eventbus. ETA for the beta release is two weeks from now. Stay tuned and we will keep you posted.

**Comment by vaquarkhan** [comment]
is above request completed ?

**Comment by adnanmansuri44** [comment]
I didnt get chance to check updates. need to implement and test event bus format.

**Comment by vaquarkhan** [comment]
It just required boto3 call and ask sns arn in  loud formation

**Comment by adnanmansuri44** [comment]
i check latest cloud formation template. unable to find the parameter for sns arn. target is only till event bus arn. from bus to other services how to fetch it? @vaquarkhan

**Comment by andrewcr7** [comment]
Clearing up an item here. An EventBridge bus is one of AHA's optional delivery channels.  Once you have delivery to your EventBridge bus configured, then configure a rule on EventBridge with your SNS topic as the target.

You can select filtering for all events on that bus when configuring the rule.  Or you can create custom patterns based on the event schema https://github.com/aws-samples/aws-health-aware/blob/main/new_aha_event_schema.md
