### ISSUE TITLE
Eventbridge message structure

### ISSUE THREAD

**Issue by lukerosser** [aws-samples/aws-health-aware#33]
At the moment the data sent to Eventbridge contains the account information as one field, in this format:

`account-name (012345678)` - That is `account_name (account_id)`

References:

https://github.com/aws-samples/aws-health-aware/blob/main/handler.py#L480-L481
https://github.com/aws-samples/aws-health-aware/blob/main/messagegenerator.py#L136

In order to action these events downstream using eventbridge we're having to pull the account id out of that field. It'd be nicer to keep these separate for example two fields: "Account name" and "Account ID"

This comment suggests some upcoming changes to eventbus structure: https://github.com/aws-samples/aws-health-aware/issues/29#issuecomment-1049847491

Are there any updates?

**Comment by jordanaroth** [comment]
New release just posted should address that
