### ISSUE TITLE
Question:  Is it possible to simulate Health events in AWS?

### ISSUE THREAD

**Issue by MikeJansen** [aws-samples/aws-health-aware#35]
This is an AWS question, but I figured you might know due to the nature of this project.

I have recently installed AHA for our organization.  I was able to test some events by setting the hours back to 4000 for one lambda run.  The problem is that only `issues` showed up for the timeframe before I had enabled Organizational View for Health.  I would like to test other event types proactively instead of waiting for them to happen in the wild.

Is there a mechanism in AWS that allows test health events to be created that come in through the API's like a normal event?  If not, how do you test the code for this project?

**Comment by mrg2k8** [comment]
Something like [this](https://catalog.us-east-1.prod.workshops.aws/workshops/dde4faf0-b40a-467c-b062-6085162d2215/en-US/lab01/step6) might be of use here.

**Comment by mrg2k8** [comment]
Asked our TAM this question and the solution was to change the `EventSearchBack` parameter from 1 hour to a value that catches some older AWS Health events.

**Comment by maplion** [comment]
I did exactly what @mrg2k8 suggested to test, but it would be nice if there was a built-in way to send it a test message so you can see the throughput to your communication endpoint.

**Comment by davedimm** [comment]
@maplion  Another option in addition to what @mrg2k8 mentioned around increasing EventSearchBack is to delete the DynamoDB entry for a particular event.  That coupled with the event search-back will cause AHA to re-process the event as if it just occurred.
