### ISSUE TITLE
AHA sample only fetches resources from first affected account

### ISSUE THREAD

**Issue by scoof** [aws-samples/aws-health-aware#36]
https://github.com/aws-samples/aws-health-aware/blob/main/handler.py#L333 - it should iterate over all accounts

**Comment by andrewcr7** [comment]
Apologies, looking at the current vs prior code here, fixed this in release 2.2

This reflects in the current function linked below where AHA iterates over all accounts.
https://github.com/aws-samples/aws-health-aware/blob/fac8c9cf803cdaf978c03d8f7113670f0e98bc30/handler.py#L405
