### ISSUE TITLE
Multi region deployment issue

### ISSUE THREAD

**Issue by yangsoodang** [aws-samples/aws-health-aware#37]
I deployed AHA with Multi region option then I found my lambda function on Secondary region failed to run. The reason is misconfiguration of lambda Environment variables. ORG_STATUS value should be “No” but was “false” even though primary region lambda ORG_STATUS value is “No”. Are there anyone who faced same as me?

**Comment by egauk** [comment]
Yes, multi-region deploy is broken.
https://github.com/aws-samples/aws-health-aware/issues/22

**Comment by jordanaroth** [comment]
Just fixed, thanks for the catch.
