### ISSUE TITLE
Health Events With No End Date

### ISSUE THREAD

**Issue by egauk** [aws-samples/aws-health-aware#41]
Some health events never provide an end date or closure event. We are having a difficult time determining when an event has ended or closed. What logic does the AWS Health Dashboard use for events without a provided end date, closure event, or status? It looks like it may use Last update time.

Example Events
RDS operational notification
OpenSearchService service software update available
VPN redundancy loss

*I see a new EventBridge schema for [aha-2.1-beta] and it looks like this may be solvable in that release.

**Comment by andrewcr7** [comment]
The usage of the time fields in AWS Health differs based on the type/category of event.  
https://docs.aws.amazon.com/health/latest/ug/cloudwatch-events-health.html#aws-health-event-schema (see startTime/endTime)

For Issue events (unexpected events that affect AWS services or resources), endTime is present indicating when the event was resolved.
For Scheduled Changes/Account Notifications (forward looking events), endTime may not be provided for events that are set in the future. The specific guidance for planned lifecycle events is to treat the startTime the change date
https://docs.aws.amazon.com/health/latest/ug/aws-health-planned-lifecycle-events.html#planned-lifecycle-event-notifications

For questions on specific events and their handling, the best way to get information on those is through an AWS support case.
https://docs.aws.amazon.com/awssupport/latest/user/case-management.html
