### ISSUE TITLE
SubscriptionRequiredException Error

### ISSUE THREAD

**Issue by richyta** [aws-samples/aws-health-aware#47]
Getting this error when I go to deploy the solution in a member account that belongs to AWS Organization. Member account does have business support plan.

[ERROR] ClientError: An error occurred (SubscriptionRequiredException) when calling the DescribeEventsForOrganization operation: 
Traceback (most recent call last):
  File "/var/task/handler.py", line 872, in main
    describe_org_events(health_client)
  File "/var/task/handler.py", line 720, in describe_org_events
    for response in org_event_page_iterator:
  File "/var/runtime/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/var/runtime/botocore/paginate.py", line 334, in _make_request
    return self._method(**current_kwargs)
  File "/var/runtime/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)

This can be closed. Issue was because we don't have a business plan in our AWS root account where AWS Organization lives.

Thanks

**Comment by jordanaroth** [comment]
Does every account in the organization have business or enterprise support? This error only happens if an account doesn't have access to the Health API

**Comment by myskamartin** [comment]
Hi @jordanaroth,

I have deployed this solution to the Management account which has the Business support plan, but I am getting this error:

`An error occured with account: 123456789012 due to: SubscriptionRequiredError : Your AWS account doesn't include the AWS Support plan required to use the AWS Health API. You must have either a Business or Enterprise Support plan.`

Does this mean all member accounts under the organization need a Business or higher support plan?

Thanks for the clarification.

**Comment by jordanaroth** [comment]
> Hi @jordanaroth,
> 
> I have deployed this solution to the Management account which has the Business support plan, but I am getting this error:
> 
> `An error occured with account: 123456789012 due to: SubscriptionRequiredError : Your AWS account doesn't include the AWS Support plan required to use the AWS Health API. You must have either a Business or Enterprise Support plan.`
> 
> Does this mean all member accounts under the organization need a Business or higher support plan?
> 
> Thanks for the clarification.

Correct, all accounts that you want to have monitored require business or enterprise support as the API call requires it. If there are certain accounts you don’t want to monitor (those that don’t have the required support level), you can include them in the exclude accounts section
