### ISSUE TITLE
Further Customizing Delivery Subscriptions

### ISSUE THREAD

**Issue by rpehrson-takeda** [aws-samples/aws-health-aware#49]
Would it be possible to have a way to easily customize the delivery based on custom metadata or perhaps AWS Organizations Account Tags to send emails to custom addresses on a per account basis? 

Use case is to deliver appropriate notifications to: Custom Account Owners, Tenant Application Owners or specific resource owners based on metadata / tags not really supported by AWS today.

I suspect it would be possible to custom code something off EventBridge and Dynamo by accountId, but I get concerned about the API limits for querying Account Tags in organizations. It would be better to have a solution to register/subscribe custom destinations in the DynamoDB.

**Comment by andrewcr7** [comment]
Yes, that requires some customization. 1) You need permissions to look up tags on accounts or resources, 2) then something like a Lambda function to do the lookup and store the data or enrich the source event.

There's a blog from last year on this topic.
https://aws.amazon.com/blogs/mt/using-tag-based-filtering-to-manage-health-monitoring-and-alerting-at-scale/
