### ISSUE TITLE
Terraform deploy to single region fails on creation of AWS Secret Manager secret for AssumeRoleArn

### ISSUE THREAD

**Issue by aouellet-tc** [aws-samples/aws-health-aware#52]
The current state of the main branch of this repo is not deployable using terraform provided in this repo.

When deploying to an Organisation member account, in a single region, using Terraform there are 2 errors:

Error 1:

```
Error: error creating Secrets Manager Secret: InvalidParameterException: Invalid replica region.

   with aws_secretsmanager_secret.AssumeRoleArn[0],
   on Terraform_DEPLOY_AHA.tf line 416, in resource "aws_secretsmanager_secret" "AssumeRoleArn":
  416: resource "aws_secretsmanager_secret" "AssumeRoleArn" {
```

Error 2:

```
 Error: Invalid index
 
   on Terraform_DEPLOY_AHA.tf line 207, in resource "aws_s3_bucket_acl" "AHA-S3Bucket-PrimaryRegion":
  207:     bucket = aws_s3_bucket.AHA-S3Bucket-PrimaryRegion[0].id
     ├────────────────
     │ aws_s3_bucket.AHA-S3Bucket-PrimaryRegion is empty tuple
 
 The given key does not identify an element in this collection value: the
 collection has no elements.
```

Please Note: Error 1 was already attempted to be fixed in this [PR-32](https://github.com/aws-samples/aws-health-aware/pull/32) of this project

**Comment by jordanaroth** [comment]
Apologies for the delays, we had to make sure that everything would work once AHA features can't be integrated into the Health Dashboard.
