### ISSUE TITLE
/AHA-LambdaFunction calls GetSecretValue even though no MS Channel is defined

### ISSUE THREAD

**Issue by saefty** [aws-samples/aws-health-aware#55]
Our cloudtrail alarming is reporting this error when deploying the lambda with only a slack url.
` arn:aws:sts::xxx:assumed-role/AHA-LambdaExecutionRole-ejo5owz1/AHA-LambdaFunction-ejo5owz1 called GetSecretValue but failed due to AccessDenied`

Cause: IAM Policy is only created when string is not empty, but the code can not know if the channel id was empty. Therfore it try to fetch it and fails.
<img width="693" alt="grafik" src="https://user-images.githubusercontent.com/25341735/236428988-4496d37a-9b3d-4020-9ae0-bad134888be6.png">

**Comment by andrewcr7** [comment]
Resolved in the above commit by pbraz
