### ISSUE TITLE
SHD updates beyond initial posting are not shown by AHA

### ISSUE THREAD

**Issue by DaniDasBoot** [aws-samples/aws-health-aware#6]
When updates are made to the Service Health Dashboard after an initial event has been opened (i.e. CloudFront goes from Green to Blue), they are not propagated or picked up by AHA and sent to the Slack webhook. Similarly, when a service/event goes back to green, that is not reflected in AHA. It appears that only the initial event notification sends out an alert via AHA but it requires the user to continue to monitor the SHD/PHD for further updates. 

Conversely, an RSS feed for Slack picks up all updates to the SHD (including after a service is not green).

**Comment by jordanaroth** [comment]
We're communicated with the Health API team to investigate this issue, it appears to have only started happening recently.

**Comment by jordanaroth** [comment]
This is fixed now, thanks for bringing it to our attention!
