### ISSUE TITLE
Add support for Splunk ingestion

### ISSUE THREAD

**Issue by XSchelin** [aws-samples/aws-health-aware#60]
Add support for ingesting AWS health alerts across organizations into Splunk.

**Comment by andrewcr7** [comment]
If you want to send Health events to Splunk, take a look at the direct integration through EventBridge. 
https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-api-destination-partners.html#api-destination-splunk

Using AWS Health organizational view for EventBridge, you can configure it in one place for all events in the organization (or filter on Eventbridge as well) without AHA's other dependencies (Dynamo, Lambda, etc.)
https://aws.amazon.com/about-aws/whats-new/2023/10/aws-health-aggregates-events-organization-eventbridge/
