### ISSUE TITLE
template v2.2.0 does not have a package available for your current platform, darwin_arm64.

### ISSUE THREAD

**Issue by latelan** [aws-samples/aws-health-aware#64]
>  Error: Incompatible provider version
>
> Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a package available for your current platform, darwin_arm64.
>
> Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.

**Comment by latelan** [comment]
Related to https://github.com/aws-samples/aws-health-aware/pull/57#issue-1702744432

**Comment by elementalvoid** [comment]
#40, #57, and #65 have all been created to fix this. All three have slightly different solutions.

At a glance, #57 fixes it the cleanest way.

The `source_files` _are not_ templates and do not need to be rendered in any way. I don't know why it was done that way in the beginning, but #40 continues to treat them as templates though it does switch to the built-in function. #65 removes the templating but is more complex using the `local_file` data source.

**Comment by andrewcr7** [comment]
Resolved in https://github.com/aws-samples/aws-health-aware/commit/cb97f2df2c096388b74d5a1c32b838d6a6bdc5bb
