### ISSUE TITLE
Is there a plan to consider using CDK as an alternative to Cloudformation deployment ?

### ISSUE THREAD

**Issue by sfu-js** [aws-samples/aws-health-aware#67]
Just wonder if anyone consider to add [CDK](https://docs.aws.amazon.com/cdk/v2/guide/home.html) deploy capability, as more and more teams started using it.

**Comment by andrewcr7** [comment]
We don't have roadmap item to add a CDK deployment feature for AHA.

If you haven't tried it already, CDK Migrate might be an option for you using the existing template
https://aws.amazon.com/blogs/devops/announcing-cdk-migrate-a-single-command-to-migrate-to-the-aws-cdk/
