### ISSUE TITLE
add "Action Required" indication to action required events 

### ISSUE THREAD

**Issue by lesh366** [aws-samples/aws-health-aware#75]
When aha sending emails to stakeholders, the important ones like: "AWS_RDS_PLANNED_LIFECYCLE_EVENT"
getting the "[Action Required]" prefix in email subject. (see pic)

Is it possible to add this indication for each event json (e.g. action required: true/false)? we would like to promote this kind of event as they are critical  

![image](https://github.com/aws-samples/aws-health-aware/assets/26593417/828f7fce-fc5e-49ed-8c40-d5ca8ec71b26)

**Comment by andrewcr7** [comment]
I understand how additional tagging like this would be useful.

The email in the screen shot is sent by AWS Health (the service) and not by AHA.  The text used in the subject line is not part of the source data available via the API.  Will check if there's another option.
