### ISSUE TITLE
Terraform Lambda doesn't include env var for channels (Slack, Teams or Chime)

### ISSUE THREAD

**Issue by diogozedan** [aws-samples/aws-health-aware#76]
On Lambda handler.py lines 702 to 709 there are calls to get secrets in case environment variables are set for channels to be communicated. (` get_secret(secret_teams_name, client) if "Teams" in os.environ else "None"`)

The Terraform code, however, doesn't populate that variable dynamically, therefore there will never be those environment variables and the notifications won't be sent.

I corrected it on my code by making the lambda variables as a local variable and merging them to the notifications channel in case they're populated.

Hope this helps.

**Comment by carlaabanes** [comment]
Found the same problem in mine too. I fixed it on my code only. 
Thanks for this post, else I would be facing a wall.

**Comment by carlaabanes** [comment]
Hi @totogtr , since we are only using teams channel in our org, i removed all other channels thats defined in the lambda functions. I also removed all other if elif conditions when sending the message.

**Comment by andrewcr7** [comment]
Committed a few terraform updates including this one to https://github.com/aws-samples/aws-health-aware/tree/terraform-updates

Will plan to include in upcoming release.
