### ISSUE TITLE
clarify which guide should we follow for delegated admin feature

### ISSUE THREAD

**Issue by ma-caylent** [aws-samples/aws-health-aware#81]
Since we are already  "delegating admin on the member account" should we follow the "Management account guide?". Keep in mind, that the links for steps #4 and #5 are broken.

Thanks

![image](https://github.com/aws-samples/aws-health-aware/assets/51483955/8974dd0d-bee8-4ff1-b712-afa617b1b7e0)

**Comment by andrewcr7** [comment]
Updated the docs and fixed the links noted above.
