### ISSUE TITLE
AHA - Deprecated Slack Integrations / new Triggers Integration

### ISSUE THREAD

**Issue by dgregan-flutter** [aws-samples/aws-health-aware#83]
Hi,

Currently the `HealthAwareStack-LambdaFunction` function that sends AHA data to Slack looks for the following `"hooks.slack.com/workflows"` & `"hooks.slack.com/services"` with the URL provided in the CFN parameter `SlackWebhookURL` and used in Lambda env variable `slack_url` as per https://github.com/aws-samples/aws-health-aware/blob/main/handler.py#L88-L123

However Slack has done some [deprecations](https://slack.com/intl/en-ie/help/articles/16787711643411-Legacy-Workflow-Builder-deprecation) around webhooks and it seems that newly created Slack workflow webhooks have web request URLs like `https://hooks.slack.com/triggers/123232` as per the screenshot
<img width="559" alt="Screenshot 2024-07-11 at 09 54 51" src="https://github.com/aws-samples/aws-health-aware/assets/129275045/1575185c-c751-4af0-92a7-3c6231d42209">

This leads me to believe that the lambda function code needs to be updated to check for `"hooks.slack.com/triggers"` to be able to invoke these new workflow URLs.

**Comment by andrewcr7** [comment]
@dgregan-flutter @lesh366

Update to this logic is in the branch https://github.com/aws-samples/aws-health-aware/tree/updates/webhooks

Will merge into a new release in the near future.

**Comment by andrewcr7** [comment]
Resolved in #94 & #96
